### PR TITLE
adds rule for unhandled promises

### LINKED ISSUE #10: Avoid ignoring returned promises
For example in this code

```ts
  async updateEntryPairs({ entry, claim, ...rest }: { claim: Claim; entry: Entry }) {
    const logger = this.logger.child({ method: 'publishEntryDownload' })
    logger.trace('started claim update hash pairs')
    this.updateClaimIdIPFSHashPairs([
      {
        claimId: claim.id,
        ipfsHash: entry.ipfsHash,
      },
    ])
    logger.trace('finished claim update hash pairs')
    return {
      claim,
      entry,
      ...rest,
    }
  }

  private async updateClaimIdIPFSHashPairs(claimIdIPFSHashPairs: ReadonlyArray<ClaimIdIPFSHashPair>) {
    const logger = this.logger.child({ method: 'updateClaimIdIPFSHashPairs' })

    logger.trace({ claimIdIPFSHashPairs }, 'Storing { claimId, ipfsHash } pairs in the DB.')

    const results = await Promise.all(
      claimIdIPFSHashPairs.map(({ claimId, ipfsHash }) =>
        this.collection.updateOne({ ipfsHash }, { $set: { claimId } }, { upsert: true })
      )
    )

    const databaseErrors = results.filter(_ => _.result.n !== 1)

    if (databaseErrors.length) logger.error({ databaseErrors }, 'Error storing { claimId, ipfsHash } pairs in the DB.')

    logger.trace({ claimIdIPFSHashPairs }, 'Storing { claimId, ipfsHash } pairs in the DB successfully.')
  }
```

`this.updateClaimIdIPFSHashPairs` returns a Promise (since it's declared as an async function). Ignoring the promise returned by `updateClaimIdIPFSHashPairs` means that any error thrown inside that function will get ignored, too. 

This is solved by just adding `await`, that'll `throw` if the promise gets rejected, which will eventually get caught higher up in the call stack and logged/retried.

Having a lint rule prevent ignored Promises would allow catching these potential bugs in Travis

### PR DESCRIPTION
**Pull request by warrenv**
Resolves #10

### Description of Changes

Adds a rule to flag unhandled promises.
https://palantir.github.io/tslint/rules/no-floating-promises/

### PR Review Checklist

* [ ] **Have you tested the changes?**
* [ ] **Is QE review required? If so, has this been reviewed by QE?** (For all new features, review by QE is required. Minor changes which already have passing functional tests may not need a new QE review -- when in doubt, loop in a QE reviewer).
* [ ] **Are there code changes that require new unit tests? If so, are those tests included?** (A separate PR for tests is not appropriate).
* [ ] **Are documentation updates required? If so, does this PR include it?** (Separate documentation PR is generally not appropriate).
* [ ] **Are the added/edited files named appropriately and located correctly in the project directory structure?**

### CODE REVIEW

**Comment by lautarodragan** [comment]
I'm testing this manually by adding this rule to the node's tsling.json but I can't get it to report a failure on an unhandled promise.

This is what my `tslint.json` looks like:

```json
{
  "extends": [
    "@po.et/tslint-rules"
  ],
  "no-floating-promises": true
}
```

It should be reporting an error on the following code:

```ts
  onBlockchainWriterTimestampSuccess = (message: any): void => {
    const messageContent = message.content.toString()
    const { fileHashes, directoryHash } = JSON.parse(messageContent)
    this.messaging.publish(Exchange.BatchWriterCompleteHashesRequest, { fileHashes, directoryHash })
  }
```

The line that starts with `this.messaging` evaluates to a Promise. My IDE correctly reports this as an ignored promise, but tslint is passing without errors.

Tried a simpler approach:

```ts
Promise.resolve('this should fail')
```

I added this line at the root of the project, outside any function or class. The linter didn't catch it.

Can you guys help me testing this? I'm not sure whether I'm doing something wrong or this rule just doesn't work.

**Comment by warrenv** [comment]
I will take a look at it.

**Comment by lautarodragan** [comment]
Thanks @warrenv!

**Comment by warrenv** [comment]
@lautarodragan The new rule needs to be wrapped inside a "rules": []

**Comment by lautarodragan** [comment]
@warrenv Do'h! You're right. It works perfectly now. Thanks!

**Pull request merged**
